const { ISSUE_TYPES } = require('./issueTypes');

const DEPARTMENTS = Object.freeze({
  SANITATION: 'Sanitation',
  CONTAINER_MAINTENANCE: 'Container Maintenance',
  EMERGENCY_ENVIRONMENT: 'Emergency / Environment',
  FIELD_OPERATIONS: 'Field Operations',
  PUBLIC_HEALTH: 'Public Health',
});

const DEPARTMENT_LIST = Object.values(DEPARTMENTS);

// Maps issue type to recommended department
const DEPARTMENT_ROUTING = Object.freeze({
  [ISSUE_TYPES.OVERFLOWING_BIN]: DEPARTMENTS.SANITATION,
  [ISSUE_TYPES.ILLEGAL_DUMPING]: DEPARTMENTS.FIELD_OPERATIONS,
  [ISSUE_TYPES.CONSTRUCTION_DEBRIS]: DEPARTMENTS.FIELD_OPERATIONS,
  [ISSUE_TYPES.SCATTERED_GARBAGE]: DEPARTMENTS.SANITATION,
  [ISSUE_TYPES.BURNING_WASTE]: DEPARTMENTS.EMERGENCY_ENVIRONMENT,
  [ISSUE_TYPES.BROKEN_CONTAINER]: DEPARTMENTS.CONTAINER_MAINTENANCE,
  [ISSUE_TYPES.INVALID]: null,
});

module.exports = { DEPARTMENTS, DEPARTMENT_LIST, DEPARTMENT_ROUTING };
